[package]
name = "smells"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"

[[test]]
name = "end_2_end_test"
path = "tests/e2e/end_2_end_test.rs"