name: Tests and Notifier
on: [push]

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit
        run: echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Run Docker container and test
        run: |
          make d_test
  
      - name: Notification Slack
        uses: ravsamhq/notify-slack-action@v2
          if: always()
          with:
            status: ${{ job.status }}
            notification_title: "Tests result for ${{ steps.commit.outputs.commit_message }}"
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}