name: Notifier
on: [push]
jobs:

  messageSlack:
    runs-on: ubuntu-latest
    steps:
    - name: Notification Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: smells_ci
        SLACK_TITLE: Hello!
        SLACK_USERNAME: BotCI
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: "It's working !"