name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Run Docker container
        run: |
          container_name=$(make d_build | grep "Container name:" | awk '{print $3}')
          docker exec $container_name bash -c 'Hello ! Container name: $container_name'
          docker stop $container_name