name: Tests and Notifier
on: [push]

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit
        run: echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Run Docker container and test
        id: test
        run: |
          test_result=$(make d_test)
          echo "::set-output name=test_result::$test_result"

      - name: Notification Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: smells_ci
          SLACK_TITLE: Test Result
          SLACK_USERNAME: BotCI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          slack_message: |
            Test results: ${{ steps.test.outputs.test_result }}
            Commit: ${{ steps.commit.outputs.commit_message }}